---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explora-ld-env
  labels:
    app: explora-ld
data:
  METRICS: 'airquality.no2::number,airquality.pm10::number'
  READINGS_TOPIC: 'cot.airquality'
  APP_NAME: 'explora-ingestion'
  KBROKERS: '10.10.139.32:9092'
  GEO_INDEX: 'quadtiling'
  PRECISION: '14'
  #REST_ENDPOINT_HOSTNAME: '0.0.0.0'
  REST_ENDPOINT_PORT: '7070'
  ENTRYPOINT_HOST: '10.10.137.122'
  ENTRYPOINT_PORT: '30070'


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: explora-ld
  name: explora-ld
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: explora-ld
    spec:
      containers:
      - env:
        - name: REST_ENDPOINT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: explora-ld-env
        image: gitlab.ilabt.imec.be:4567/lordezan/explora-ld:latest
        command: ["sh"]
        args: ["-c", "java -cp /usr/local/service/explora-ld-0.1-jar-with-dependencies.jar ingestion.IngestStream --metric-list ${METRICS} --geo-index ${GEO_INDEX} --precision ${PRECISION} --cleanup"]
        name: explora-ld
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "2"
        ports:
        - containerPort: 7070
          name: explora-ld
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
